### ISSUE TITLE
无法解析虾米音乐 Invalid character entity

### ISSUE THREAD

**Issue by cdiscrete** [naoyeye/xiamiRun#1]
```
info: Starting app...

info: 
info: 
info:    Sails              <|
info:    v0.10.5             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/var/www/xiamiRun`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Tue Apr 21 2015 22:58:03 GMT-0400 (EDT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
connect deprecated res.headerSent: use standard res.headersSent node_modules/sails/node_modules/express/node_modules/connect/lib/proto.js:129:22
connect deprecated res.on("header"): use on-headers npm module instead node_modules/sails/node_modules/express/node_modules/connect/lib/middleware/session.js:247:9
errors [Error: Unexpected close tag
Line: 128
Column: 7
Char: >]
errors [Error: Unexpected close tag
Line: 128
Column: 7
Char: >]
errors [Error: Invalid character entity
Line: 130
Column: 120
Char: =]
errors [Error: Invalid character entity
Line: 130
Column: 127
Char: &]
errors [Error: Invalid character entity
Line: 130
Column: 135
Char: &]
errors [Error: Invalid character entity
Line: 147
Column: 78
Char: =]
errors [Error: Invalid character entity
Line: 162
Column: 33
Char: ']
errors [Error: Invalid character entity
Line: 162
Column: 67
Char: ']

/var/www/xiamiRun/node_modules/xmlreader/node_modules/sax/lib/sax.js:912
  if (this.error) throw this.error
                            ^
Error: Invalid character entity
Line: 162
Column: 67
Char: '
    at error (/var/www/xiamiRun/node_modules/xmlreader/node_modules/sax/lib/sax.js:642:8)
    at strictFail (/var/www/xiamiRun/node_modules/xmlreader/node_modules/sax/lib/sax.js:662:22)
    at Object.write (/var/www/xiamiRun/node_modules/xmlreader/node_modules/sax/lib/sax.js:1335:11)
    at Object.exports.read (/var/www/xiamiRun/node_modules/xmlreader/xmlreader.js:157:12)
    at IncomingMessage.<anonymous> (/var/www/xiamiRun/api/controllers/XiamiController.js:41:27)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by naoyeye** [comment]
![screen shot 2015-04-22 at 4 12 28 pm](https://cloud.githubusercontent.com/assets/434428/7269910/6aaf56d8-e90a-11e4-8363-d000efa9fe3a.png)

试了一下，我这边是可以的。
测试地址是 `http://localhost:1337/xiami/run?song=http://www.xiami.com/song/87855`

**Comment by naoyeye** [comment]
如果你的服务器是运行在国外的话，这个服务访问虾米的音乐 url 时因为版权问题无法正常读取页面。
不知道是不是这个原因。
当时我是跑在阿里云上的。

**Comment by cdiscrete** [comment]
喔我主机是在国内……考虑重开国内的主机吗？

**Comment by naoyeye** [comment]
@cdiscrete 暂时还不会开。因为这个服务几乎没什么访问量，一个月最多也就我自己用的那么一两次。

你可以在 https://github.com/naoyeye/xiamiRun/blob/master/api/controllers/XiamiController.js 这个文件里 console.log() 看下访问页面的时候出了什么问题。看你上面的 log 应该是解 析 xml 的时候出错了。

line 40:
```
resp.on('end', function() {
    console.log('xml=', xml); // 在这里加一行 然后看下输出的 xml 是什么
    xmlreader.read(xml, function(errors, responsive){
        .......
    }
}
```


正常的话会是这样：

![screen shot 2015-04-22 at 5 15 17 pm](https://cloud.githubusercontent.com/assets/434428/7271010/30389cf4-e913-11e4-9d26-62acf2f66535.png)

**Comment by naoyeye** [comment]
@cdiscrete 我正在 leanCloud 上搭一个音乐解析服务，完成后告诉你地址

**Comment by naoyeye** [comment]
http://xiamirun.avosapps.com/run?song=http://www.xiami.com/song/1774205606
